name: t360 backend
 
permissions:
  id-token: write
  contents: read
 
on:
  pull_request:
    branches:
      - dev
      - qa-release
      - qa-release-*
    types:
      - closed   # fires when PR is closed, merged check happens in job condition
 
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (prod only)"
        required: true
        type: choice
        options: [prod]
      branch:
        description: "Prod branch to deploy (must start with prod_*)"
        required: true
        type: string
 
jobs:
  resolve_enviornment:
    name: Deploy to Backend lambda
    runs-on: ubuntu-latest
    # needs: test-and-build
    if: |
      (
        github.event_name == 'pull_request' &&
        github.event.pull_request.merged == true &&
        (
          github.base_ref == 'dev' ||
          github.base_ref == 'qa-release' ||
          startsWith(github.base_ref, 'qa-release-')
        )
      ) ||
      (
        github.event_name == 'workflow_dispatch' &&
        github.event.inputs.environment == 'prod'
      )
 
    steps:
      - uses: actions/checkout@v4
 
      - name: Determine Environment
        env:
          EVENT_NAME: ${{ github.event_name }}
          BASE_REF: ${{ github.base_ref }}
          INPUT_BRANCH: ${{ github.event.inputs.branch }}  # used for prod
        run: |
          if [[ "$EVENT_NAME" == "pull_request" ]]; then
            if [[ "$BASE_REF" == "dev" ]]; then
              ENV=$BASE_REF
              STAGE=$BASE_REF
              BRANCH="$BASE_REF"
              ROLE="${{ secrets.AWS_NONPROD_ROLE_ARN }}"
 
            elif [[ "$BASE_REF" == "qa-release" || "$BASE_REF" =~ ^qa-release- ]]; then
              ENV="${BASE_REF%%-*}"
              BRANCH="$BASE_REF"
              ROLE="${{ secrets.AWS_NONPROD_ROLE_ARN }}"
            fi
            
 
          elif [[ "$EVENT_NAME" == "workflow_dispatch" ]]; then
            ENV=prod
            BRANCH="$INPUT_BRANCH"
 
            if [[ "$BRANCH" != prod_* ]]; then
              echo "❌ Invalid prod branch: $BRANCH"
              exit 1
            fi
 
            ROLE="${{ secrets.AWS_PROD_ROLE_ARN }}"
            SECRET_NAME="t360-almanac-prod"
          fi
 
          echo "ENV=$ENV" >> $GITHUB_ENV
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          echo "ROLE=$ROLE" >> $GITHUB_ENV
          echo "STAGE=$STAGE" >> $GITHUB_ENV

          cat $GITHUB_ENV
 
          echo "✅ Deploying stage $STAGE from branch $BRANCH"
